schema: schema.graphql
extensions:
   endpoints:
      Default GraphQL Endpoint:
         url: http://172.30.1.34:8081:8000/graphql
         headers:
            user-agent: JS GraphQL
         introspect: false
